### ISSUE TITLE
Review microtask-4

### ISSUE THREAD

**Issue by SteveKola** [SteveKola/grimoirelab-microtasks#6]
https://github.com/SteveKola/grimoirelab-microtasks/blob/main/microtask4/README.md

What do you think, @vchrombie?

**Comment by SteveKola** [comment]
@vchrombie, why did so many of the backend tests fail? And is there anything I could do concerning that?

One of the frontend tests failed. Why?

**Comment by vchrombie** [comment]
Hi @SteveKola, thanks for asking.

> @vchrombie, why did so many of the backend tests fail? And is there anything I could do concerning that?

I think you have a different python version, can you please confirm what version of python are using for the project?

As of now, the tests work fine with python 3.6. It is because there are some fields that are changed or might be deprecated in the next version. We are aware of it and checking to resolve this. I can confirm the tests are working fine, we have the CI setup with github actions and the build seems to be good.

Workflow File: https://github.com/chaoss/grimoirelab-sortinghat/blob/muggle/.github/workflows/ci.yml
Github Action Build: https://github.com/chaoss/grimoirelab-sortinghat/runs/2228818350?check_suite_focus=true

> One of the frontend tests failed. Why?

Strange, the frontend test suite also works fine with the CI.

GitHub Action Build: https://github.com/chaoss/grimoirelab-sortinghat/runs/2228818498?check_suite_focus=true

**Comment by vchrombie** [comment]
Also, just make sure you have all the correct versions of the dependencies installed. Sometimes, we have the wrong version and it has a direct effect on the test suite.

**Comment by SteveKola** [comment]
> I think you have a different python version, can you please confirm what version of python are using for the project?

My Python version is 3.8.5. Could that be the reason?
If yes, does that mean I'd have to delete my current virtualenv to create a new one with Python 3.6?

> Also, just make sure you have all the correct versions of the dependencies installed. Sometimes, we have the wrong version and it has a direct effect on the test suite.

I installed all the dependencies using `poetry install`, so I think it'd have installed the correct versions except the `poetry.lock` file is a tad inacurrate.

**Comment by vchrombie** [comment]
Also, reviewing the microtask-4, it looks good to me.

Thanks for taking the effort to write the steps in detail. The task was to make you go through the development setup of the tool (running test suite was not really required, but I appreciate the effort).

**Comment by vchrombie** [comment]
> My Python version is 3.8.5. Could that be the reason?

Might be.

> If yes, does that mean I'd have to delete my current virtualenv to create a new one with Python 3.6?

If you have the time to try this, please go ahead.

> I installed all the dependencies using poetry install, so I think it'd have installed the correct versions except the poetry.lock file is a tad inacurrate.

If you are in any doubt, just delete the existing virtual env and the `poetry.lock` file and run `poetry install` again. It should serve as a fresh installation.

**Comment by SteveKola** [comment]
Alright. I'll close this now. Thank you for your elaborate explanations
